"""Sample lawyer seed data (Munich / Germany).

This realistic-but-fictional dataset lets the directory and search features
work end-to-end without running the live scraper. Real data is populated by
LawyerService.sync_live(). The records are shaped exactly like scraper output
so they exercise the same upsert path.
"""
from __future__ import annotations

import hashlib

from app.scraper.rak_muenchen import ParsedLawyer


def _key(profile_url: str) -> str:
    return hashlib.sha256(profile_url.encode()).hexdigest()[:32]


_RAW = [
    {
        "name": "Dr. Anna Müller",
        "law_firm": "Müller & Partner Rechtsanwälte",
        "city": "München",
        "email": "a.mueller@mueller-partner.example",
        "phone": "+49 89 1234567",
        "website": "https://mueller-partner.example",
        "address": "Maximilianstraße 12, 80539 München",
        "languages": "German, English",
        "specializations": ["Employment", "Labour Law"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/mueller",
    },
    {
        "name": "Stefan Becker",
        "law_firm": "Becker Legal",
        "city": "München",
        "email": "becker@becker-legal.example",
        "phone": "+49 89 7654321",
        "website": "https://becker-legal.example",
        "address": "Sendlinger Str. 5, 80331 München",
        "languages": "German, English, Turkish",
        "specializations": ["Immigration", "Family"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/becker",
    },
    {
        "name": "Dr. Laura Schneider",
        "law_firm": "Schneider Mietrecht",
        "city": "München",
        "email": "schneider@schneider-mietrecht.example",
        "phone": "+49 89 2223344",
        "website": "https://schneider-mietrecht.example",
        "address": "Leopoldstraße 50, 80802 München",
        "languages": "German",
        "specializations": ["Rental", "Tenancy Law"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/schneider",
    },
    {
        "name": "Michael Hoffmann",
        "law_firm": "Hoffmann & Co.",
        "city": "Augsburg",
        "email": "m.hoffmann@hoffmann-co.example",
        "phone": "+49 821 998877",
        "website": "https://hoffmann-co.example",
        "address": "Maximilianstraße 40, 86150 Augsburg",
        "languages": "German, English",
        "specializations": ["Consumer", "Insurance"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/hoffmann",
    },
    {
        "name": "Dr. Julia Wagner",
        "law_firm": "Wagner Verkehrsrecht",
        "city": "München",
        "email": "wagner@wagner-verkehr.example",
        "phone": "+49 89 4455667",
        "website": "https://wagner-verkehr.example",
        "address": "Schwanthalerstr. 10, 80336 München",
        "languages": "German, French",
        "specializations": ["Traffic", "Insurance"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/wagner",
    },
    {
        "name": "Thomas Fischer",
        "law_firm": "Fischer Steuer & Recht",
        "city": "München",
        "email": "fischer@fischer-steuer.example",
        "phone": "+49 89 5566778",
        "website": "https://fischer-steuer.example",
        "address": "Brienner Str. 25, 80333 München",
        "languages": "German, English",
        "specializations": ["Tax", "Business"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/fischer",
    },
    {
        "name": "Dr. Petra Klein",
        "law_firm": "Klein Familienrecht",
        "city": "Nürnberg",
        "email": "klein@klein-familie.example",
        "phone": "+49 911 334455",
        "website": "https://klein-familie.example",
        "address": "Königstraße 60, 90402 Nürnberg",
        "languages": "German, English, Spanish",
        "specializations": ["Family", "Employment"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/klein",
    },
    {
        "name": "Andreas Weber",
        "law_firm": "Weber Wirtschaftskanzlei",
        "city": "München",
        "email": "weber@weber-wirtschaft.example",
        "phone": "+49 89 6677889",
        "website": "https://weber-wirtschaft.example",
        "address": "Promenadeplatz 8, 80333 München",
        "languages": "German, English, Italian",
        "specializations": ["Business", "Consumer"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/weber",
    },
    {
        "name": "Dr. Elif Yildirim",
        "law_firm": "Yildirim Arbeitsrecht",
        "city": "Berlin",
        "email": "yildirim@yildirim-arbeitsrecht.example",
        "phone": "+49 30 1122334",
        "website": "https://yildirim-arbeitsrecht.example",
        "address": "Kurfürstendamm 21, 10719 Berlin",
        "languages": "German, Turkish, English",
        "specializations": ["Employment", "Labour Law"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/yildirim",
    },
    {
        "name": "Sergej Wolkow",
        "law_firm": "Wolkow Migrationsrecht",
        "city": "Berlin",
        "email": "wolkow@wolkow-migration.example",
        "phone": "+49 30 2233445",
        "website": "https://wolkow-migration.example",
        "address": "Karl-Marx-Allee 90, 10243 Berlin",
        "languages": "German, Russian, Ukrainian, English",
        "specializations": ["Immigration", "Asylum"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/wolkow",
    },
    {
        "name": "Dr. Katarzyna Nowak",
        "law_firm": "Nowak Familienrecht",
        "city": "Hamburg",
        "email": "nowak@nowak-familie.example",
        "phone": "+49 40 3344556",
        "website": "https://nowak-familie.example",
        "address": "Mönckebergstraße 7, 20095 Hamburg",
        "languages": "German, Polish, English",
        "specializations": ["Family", "Divorce"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/nowak",
    },
    {
        "name": "Malte Hansen",
        "law_firm": "Hansen Seerecht & Handel",
        "city": "Hamburg",
        "email": "hansen@hansen-seerecht.example",
        "phone": "+49 40 4455667",
        "website": "https://hansen-seerecht.example",
        "address": "Speicherstadt 3, 20457 Hamburg",
        "languages": "German, English",
        "specializations": ["Business", "Contract Law"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/hansen",
    },
    {
        "name": "Dr. Ioana Popescu",
        "law_firm": "Popescu Mietrecht Köln",
        "city": "Köln",
        "email": "popescu@popescu-miete.example",
        "phone": "+49 221 5566778",
        "website": "https://popescu-miete.example",
        "address": "Hohe Straße 44, 50667 Köln",
        "languages": "German, Romanian, English",
        "specializations": ["Rental", "Tenancy Law"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/popescu",
    },
    {
        "name": "Jonas Schreiber",
        "law_firm": "Schreiber Strafrecht",
        "city": "Köln",
        "email": "schreiber@schreiber-strafrecht.example",
        "phone": "+49 221 6677889",
        "website": "https://schreiber-strafrecht.example",
        "address": "Ringstraße 12, 50674 Köln",
        "languages": "German, English",
        "specializations": ["Criminal"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/schreiber",
    },
    {
        "name": "Dr. Samira Haddad",
        "law_firm": "Haddad Familien- & Erbrecht",
        "city": "Frankfurt am Main",
        "email": "haddad@haddad-recht.example",
        "phone": "+49 69 7788990",
        "website": "https://haddad-recht.example",
        "address": "Zeil 80, 60313 Frankfurt am Main",
        "languages": "German, Arabic, English, French",
        "specializations": ["Family", "Inheritance"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/haddad",
    },
    {
        "name": "Felix Krüger",
        "law_firm": "Krüger Bank- & Kapitalmarktrecht",
        "city": "Frankfurt am Main",
        "email": "krueger@krueger-bankrecht.example",
        "phone": "+49 69 8899001",
        "website": "https://krueger-bankrecht.example",
        "address": "Mainzer Landstraße 50, 60325 Frankfurt am Main",
        "languages": "German, English",
        "specializations": ["Banking", "Business"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/krueger",
    },
    {
        "name": "Dr. Valentina Rossi",
        "law_firm": "Rossi Medizinrecht",
        "city": "Stuttgart",
        "email": "rossi@rossi-medizinrecht.example",
        "phone": "+49 711 9900112",
        "website": "https://rossi-medizinrecht.example",
        "address": "Königstraße 15, 70173 Stuttgart",
        "languages": "German, Italian, English",
        "specializations": ["Medical Malpractice", "Insurance"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/rossi",
    },
    {
        "name": "Bastian Lehmann",
        "law_firm": "Lehmann Patent- & Markenrecht",
        "city": "Stuttgart",
        "email": "lehmann@lehmann-ip.example",
        "phone": "+49 711 1122003",
        "website": "https://lehmann-ip.example",
        "address": "Schlossplatz 4, 70173 Stuttgart",
        "languages": "German, English",
        "specializations": ["Intellectual Property", "Business"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/lehmann",
    },
    {
        "name": "Dr. Olena Kovalenko",
        "law_firm": "Kovalenko Sozialrecht",
        "city": "Düsseldorf",
        "email": "kovalenko@kovalenko-sozial.example",
        "phone": "+49 211 2233114",
        "website": "https://kovalenko-sozial.example",
        "address": "Königsallee 60, 40212 Düsseldorf",
        "languages": "German, Ukrainian, Russian, English",
        "specializations": ["Social Security", "Employment"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/kovalenko",
    },
    {
        "name": "Paul Zimmermann",
        "law_firm": "Zimmermann Datenschutzrecht",
        "city": "Düsseldorf",
        "email": "zimmermann@zimmermann-datenschutz.example",
        "phone": "+49 211 3344225",
        "website": "https://zimmermann-datenschutz.example",
        "address": "Berliner Allee 20, 40212 Düsseldorf",
        "languages": "German, English",
        "specializations": ["Data Protection", "Business"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/zimmermann",
    },
    {
        "name": "Dr. Camille Girard",
        "law_firm": "Girard Immobilienrecht",
        "city": "Leipzig",
        "email": "girard@girard-immobilien.example",
        "phone": "+49 341 4455336",
        "website": "https://girard-immobilien.example",
        "address": "Grimmaische Straße 10, 04109 Leipzig",
        "languages": "German, French, English",
        "specializations": ["Real Estate", "Rental"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/girard",
    },
    {
        "name": "Robert Schulze",
        "law_firm": "Schulze Verkehrsrecht Dresden",
        "city": "Dresden",
        "email": "schulze@schulze-verkehr.example",
        "phone": "+49 351 5566447",
        "website": "https://schulze-verkehr.example",
        "address": "Prager Straße 18, 01069 Dresden",
        "languages": "German, English",
        "specializations": ["Traffic", "Insurance"],
        "profile_url": "https://www.rak-muenchen.de/anwaltsverzeichnis/profil/schulze",
    },
]


def sample_lawyers() -> list[ParsedLawyer]:
    out: list[ParsedLawyer] = []
    for raw in _RAW:
        url = raw["profile_url"]
        content_hash = hashlib.sha256(
            (raw["name"] + raw["city"] + ",".join(raw["specializations"])).encode()
        ).hexdigest()[:32]
        out.append(
            ParsedLawyer(
                source_key=_key(url),
                name=raw["name"],
                law_firm=raw["law_firm"],
                city=raw["city"],
                email=raw["email"],
                phone=raw["phone"],
                website=raw["website"],
                address=raw["address"],
                profile_url=url,
                languages=raw["languages"],
                specializations=raw["specializations"],
                content_hash=content_hash,
            )
        )
    return out
